version: "3"

services:
  php-apache:
    image: php:apache
    countainer_name: my-php-app
    ports:
      - 80:80
    volumes:
      - ./var/www/html/script.php

  mysql:
    image: mysql
    container_name: mysql-db
    ports:
      - "3306:3306"
    environnement:
      MYSQL_ROOT_PASSWORD: root2
      MYSQL_DATABASE: database_tp2
      MYSQL_USER: root
      MYSQL_PASSWORD: root
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_USER: oui
      MYSQL_PASSWORD: oui